### ISSUE TITLE
Doble h1

### ISSUE THREAD

**Issue by JPradillo** [iesgrancapitan-entornos/2023-24-pr-ctica-5-github-issues-Hanaede#1]
https://github.com/iesgrancapitan-entornos/2023-24-pr-ctica-5-github-issues-Hanaede/blob/7e16c7c9485e638af4e35d62483824cd8cacf4a2/index.html#L15

No puede haber dos h1 en un mismo documento. Podrías poner por ejemplo un h2 para que parezca como un subtítulo.

**Comment by Hanaede** [comment]
Vale, apuntado para futuros cambios.

**Comment by JPradillo** [comment]
Genial, estaré pendiente de los cambios.
