### ISSUE TITLE
h1 repetido

### ISSUE THREAD

**Issue by JPradillo** [iesgrancapitan-entornos/2023-24-pr-ctica-5-github-issues-Hanaede#2]
https://github.com/iesgrancapitan-entornos/2023-24-pr-ctica-5-github-issues-Hanaede/blob/7e16c7c9485e638af4e35d62483824cd8cacf4a2/index.html#L19

Un html solo debe tener un único h1 por lo que debería cambiarse por un h2 por ejemplo o un h3. 
@Hanaede

**Comment by Hanaede** [comment]
Lo soluciona en un momento.

**Comment by JPradillo** [comment]
Genial, estaré pendiente de los cambios.
